---
version: "3"
services:
 devopsdb:
   image: ramyakolla3702/dockerwebapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: ramyakolla3702/dockerwebapp:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
